# Simple workflow for deploying static content to GitHub Pages
name: Final Main repo maintenance

on:
  # Runs on pushes targeting the default branch
  # push:
  #  branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  one:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Configure GitHub Pages
        id: pages
        uses: actions/configure-pages@v3        
      - name: Show page
        run: echo "${{ steps.pages.outputs.base_url }}"